FROM python:3.10

WORKDIR /code

# Requirements copy & install
COPY ./backend/requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Whisper audio processing ke liye ffmpeg
RUN apt-get update && apt-get install -y ffmpeg

# Saara project 
COPY . /code

# Dynamic port binding for Hugging Face
CMD ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "7860"]
